roots = [
  "^Main.main$",          # Main executable entry points
  "^Main\\..*",           # All exports from Main modules (demo code)
  "^EventualConsistency\\..*",  # Eventual consistency demo module
  "^Paths_.*",            # Cabal-generated paths modules

  # Test modules - all test code is intentionally used
  "^Test\\..*",

  # MuniHac demo code - all exported for demonstration purposes
  "^MuniHac\\..*",

  # Benchmark entry points and utilities
  "^Backends\\..*",       # Benchmark backend implementations
  "^Core\\..*",           # Benchmark core utilities (metrics, etc)
  "^Scenarios\\..*",      # Benchmark scenarios
  "^Bench\\..*",          # Legacy benchmark modules
  "^Analysis\\..*",       # Benchmark CSV analysis utilities

  # Internal modules used by backend implementations (cross-package usage)
  # These are exported from hindsight package but used by store backends
  "^Hindsight\\.Store\\.Internal\\..*",
]

type-class-roots = true


unused-types = true

