version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hindsight-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hindsight
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hindsight-network

  # Long-running subscription example with GHC 9.10
  app:
    build:
      context: .
      dockerfile: Dockerfile.ghc-9.12
    container_name: hindsight-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: hindsight
      API_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - hindsight-network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  hindsight-network:
    driver: bridge
