name: Deploy Hindsight Website to GitHub Pages

on:
  # Trigger on pushes to main branch that affect website or docs
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - 'docs/**'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/deploy-site.yaml'

  # Allow manual triggering
  workflow_dispatch:

# Required permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: hindsight-es
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build website executable with Nix
        run: |
          nix build .#hindsight-website

      - name: Build Sphinx documentation
        run: |
          nix develop .#ci --command bash -c "cd docs && make html"

      - name: Generate Hakyll site
        run: |
          cd website && ../result/bin/site build

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: website/_site

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    # Deploy to the GitHub Pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
